### ISSUE TITLE
Alt-left should align to the next left side

### ISSUE THREAD

**Issue by koppor** [baderas/autohotkey-scripts#1]
If the center of the window is in the left third part, and I press <kbd>win</kbd><kbd>cursor left</kbd>, the window is NOT placed at the left border, but moved to the screen left of my current screen.

The reason seems to be that the center is used. Why not using the left border when moving left?

**Comment by baderas** [comment]
Fixed with 2a569d597e3b4fca7a301ca730aa0d87813aa5a3

**Comment by koppor** [comment]
If Microsoft Word, Firefox, or Chrome are positioned in the middle (2nd 1/3), then it cannot be moved to the left.

ConEmu does not go to 1/3 at all (which is OK for me)
