### ISSUE TITLE
ReadMe.md link issue

### ISSUE THREAD

**Issue by MySecretUsername** [baderas/autohotkey-scripts#2]
Hello, 

Thank you for sharing.

Your ReadMe.md has a link to Toogle hidden files which is 

> https://github.com/baderas/autohotkey-scripts/blob/master/ToggleHiddenFiles.ahk

Whereas the file is actually spelt Toogle, not Toggle, so the correct link is (unless you correct the spelling)

> https://raw.githubusercontent.com/baderas/autohotkey-scripts/master/ToogleHiddenFiles.ahk

Thank you.

**Comment by koppor** [comment]
I think, the filename should just be fixed.

**Comment by baderas** [comment]
The filename is fixed now.
