### ISSUE TITLE
Non-resizable Windows should just be repositioned, not resized

### ISSUE THREAD

**Issue by koppor** [baderas/autohotkey-scripts#3]
If I move the VeryCrypt main window with win left/right, it also gets resized, but I cannot change the size back to the normal window size. I think, non-resizable windows should just be moved, not resized.

![grabbed_20161001-133832](https://cloud.githubusercontent.com/assets/1366654/19013835/db4b32be-87dc-11e6-9b8a-78fcf2589122.png)

**Comment by baderas** [comment]
I think its related to the following question: http://stackoverflow.com/questions/22084151/autohotkey-to-resize-window-with-child-windows

It seems that there is no mechanism that autohotkey can use to ask if a window reports itself as resizable or not. Therefore the script can't determine if a window is resizable or not (without black/whitelisting).
